# Generated by Django 5.1.6 on 2025-03-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_id',
            field=models.CharField(max_length=250),
        ),
    ]
